### ISSUE TITLE
Comp clean up function

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_black_rockfish_density#3]
https://github.com/commfish/seak_black_rockfish_density/blob/15f382ff29276de368268e96054c408b4081acde/code/helper.r#L15

I understand you're not using this function, but if I understand it correctly you weight the age comps by the sample sizes in each year to get one age comp. Is that correct? Just making sure I'm following the code.

**Comment by ben-williams** [comment]
yep, weighted age comps by annual sample sizes. Also explored annual age comps, but not enough info in the dataset(s) for that - gets weird between comm and sportfish data
