### ISSUE TITLE
Growth parameters and choice of plus group age

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_black_rockfish_density#4]
Growth starting values:
An Linf of 54 or 55 seems high given the data, but perhaps I'm wrong (this is the only brf data I've ever seen). I think you'd get a comparable fit at Linf of 20-30. 

Along the same lines I think 30 may be a little high for your plus group. I would recommend adjusting this to correspond roughly to your Linf and/or age at which all fish are mature (whichever is greater). The guidance I was given about plus groups is that they should capture the full scope of these dynamics and represent most of your data.

**Comment by ben-williams** [comment]
I'm not aware of methods for fitting vbl growth curves utilizing age plus-groups, and I would not be comfortable doing so (and don't think it appropriate) without the incorporation of measurement error (e.g., Cope and Punt 2007. Admitting ageing error when fitting growth curves: an example using the von Bertalanffy growth function with random effects.) something I do not possess for this species. 

Oh, 30 is not a plus group, it is a max age. There is some question as to whether (or how frequently) black rockfish females survive to older ages - males are regularly found in the 40s/50s.
