### ISSUE TITLE
DATA_SCALAR vs DATA_INTEGER

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_black_rockfish_density#8]
Ok this one is important. 

DATA_SCALAR = Type (also DATA_VECTOR)
DATA_INTEGER = int (also DATA_IVECTOR)

These should be DATA_SCALARs:
```
  // weight & maturity
  DATA_INTEGER(lw_int);
  DATA_INTEGER(lw_slope);
  DATA_INTEGER(mat_b0);
  DATA_INTEGER(mat_b1);
```
https://kaskr.github.io/adcomp/group__macros.html#gae361b76344dbd1c7cbf5073949211641

**Comment by ben-williams** [comment]
makes sense, thanks
